### ISSUE TITLE
Savings Account

### ISSUE THREAD

**Issue by lee741** [Databaes-FNB/bank-acc-manager#5]
### Savings Account (`BankAccount`)
- Define a base class to hold common attributes and methods.
- Implement specific account behaviors.
- Document definitions and uses.

- **Establish methods for class `SavingsAccount`**: 
- Add attributes like `accountNumber`, `balance`, and methods like `deposit`, `withdraw`, and `transfer`.

## Expected time allowance: 2 days

**Comment by KevinM55** [comment]
Savings Account class went through testing and debugging and issues were resolved. Now in integration mode
