### ISSUE TITLE
Meeting Notes

### ISSUE THREAD

**Issue by lee741** [Databaes-FNB/bank-acc-manager#9]
## Notes from team meeting (14:00, 25/11/2024)

# Commit:
- **`Super class BankAccount`**: @KevinM55 will upload the super class with areas for development by COB. 
- **`Subclass SavingsAccount`**:  @lee741 will upload the sub class with areas for development by COB.  

- **Transfer Functionality**: Each member agreed on the structure of the transfer functionality across accounts that will be defined and used within each account.  
- **Initializing Account Number**: The objective is to generate a random account number for new users that has not been allocated before for new account members. This still needs to be addressed.
- **Utilizing interest rate**: The objective is to define the type and functionality of an initialized interest rate for the savings account. Furthermore, the frequency of the interest rate affecting the balance of the savings account musty be finalized.
- **Overdraft Functionality**: This applies to the cheque account and still needs to be addressed.
- **Initializing Balance**: The team has agreed that any account will have an initial balance of zero.

- **Feedback**: Each member will provide periodic feedback highlighting their progress on the areas mentioned above as well as on the scheduled meeting on 26/11/2024.

**Comment by lee741** [comment]
## Notes from team meeting (14:00, 26/11/2024)


# Commit:
- **`Super class BankAccount`**: @KevinM55 will upload the super class with areas for development by COB. 
- **`Subclass SavingsAccount`**:  @lee741 and @desreedimaky  will upload the sub class with areas for development by COB.  
- **`Subclass ChequeAccount`**:  @Tumisang9x and @NompiloZondo-Dev  will upload the sub class with areas for development by COB.  
- **`Main driver`**:  @NkosinathiSeptember23  will upload the main driver.  

- **Utilizing interest rate**: The objective is to define the type and functionality of an initialized interest rate for the savings account. Furthermore, the frequency of the interest rate affecting the balance of the savings account musty be finalized.
- **Overdraft Functionality**: This applies to the cheque account and still needs to be addressed.
- **Bank Charges**: Savings account will not have any charges associated with it while the cheque account has charges associated with different functions such as withdrawals and deposits. 
- **Exception Handling**: Main driver needs to handle cases when user input differs from anticipated responses.



- **Feedback**: Each member will provide periodic feedback highlighting their progress on the areas mentioned above as well as on the scheduled meeting on 27/11/2024.

**Comment by Tumisang9x** [comment]
No meeting was scheduled for 28/11/2024.

**Comment by Tumisang9x** [comment]
No further meetings for this project
